name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: True
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Docker compose Build and Push
        run: |
          cd ./API
          docker-compose build --no-cache
          docker-compose push

  docker-pull-ec2:
    needs: docker-compose-build
    runs-on: ubuntu-latest
    steps:
      - name: Creating SSH Configuration File
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deployment.pem
          chmod 600 ~/.ssh/deployment.pem
          cat >> ~/.ssh/config << END
          Host deploy_ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deployment.pem
            StrictHostKeyChecking no
          END

      - name: Deploy to EC2
        run: |
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "if [ -e temp/ ]; then rm -rf temp/; fi"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "mkdir temp/"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "git clone git@github.com:Rian021102/Smoker-Detection-Bio-Signs.git temp/"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "rsync -a ./temp/ ./Smoker-Detection-Bio-Signs/"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "rm -rf temp/"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "cd Smoker-Detection-Bio-Signs/ && git lfs pull"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "cd Smoker-Detection-Bio-Signs/ && sudo docker-compose rm -sf API"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "cd Smoker-Detection-Bio-Signs/ && sudo docker rmi Rian021102/smoker-detection-bio-signs-api"
          ssh ec2-108-137-69-107.ap-southeast-3.compute.amazonaws.com "cd Smoker-Detection-Bio-Signs/ && sudo docker-compose pull && sudo docker-compose up -d"

