name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Compose Build and Push
        run: |
          docker-compose build --no-cache
          docker-compose push

  docker-pull-ec2:
    needs: docker-compose-build
    runs-on: ubuntu-latest
    steps:
      - name: Creating SSH Configuration File
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        run:
          - name: Create SSH directory
            run: mkdir -p ~/.ssh
          - name: Write SSH private key to file
            run: echo "$SSH_KEY" > ~/.ssh/RianRkey.pem
          - name: Set permissions for SSH private key
            run: chmod 600 ~/.ssh/RianRkey.pem
          - name: Configure SSH
            run: |
              cat >> ~/.ssh/config << END
              Host deploy_ec2
                HostName $SSH_HOST
                User $SSH_USER
                IdentityFile ~/.ssh/RianRkey.pem
                StrictHostKeyChecking no
              END
          - name: Deploy to EC2
            run: |
              ssh deploy_ec2 "mkdir temp/"
              ssh deploy_ec2 "git clone git@github.com:Rian021102/Smoker-Detection-Bio-Signs.git temp/"
              ssh deploy_ec2 "rsync -a ./temp/ ./Smoker-Detection-Bio-Signs/"
              ssh deploy_ec2 "rm -rf temp/"
              ssh deploy_ec2 "cd Smoker-Detection-Bio-Signs/ && git lfs pull"
              ssh deploy_ec2 "cd Smoker-Detection-Bio-Signs/ && sudo docker compose rm -sf api"
              ssh deploy_ec2 "cd Smoker-Detection-Bio-Signs/ && sudo docker rmi Rian021102/smoker-detection-bio-signs_api"
              ssh deploy_ec2 "cd Smoker-Detection-Bio-Signs/ && sudo docker compose pull && sudo docker compose up -d"
